-- MySQL Script generated by MySQL Workbench
-- Fri Mar 30 14:45:03 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

DROP DATABASE IF EXISTS `cop4331`;
CREATE DATABASE `cop4331`;
USE `cop4331`;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Users` ;

CREATE TABLE IF NOT EXISTS `Users` (
  `userID` INT NOT NULL,
  `fName` VARCHAR(45) NULL,
  `lName` VARCHAR(45) NULL,
  `userName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(64) NULL,
  PRIMARY KEY (`userID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Events` ;

CREATE TABLE IF NOT EXISTS `Events` (
  `eventID` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `start_date` DATE NULL,
  `end_date` DATE NULL,
  `start_time` TIME(0) NULL,
  `end_time` TIME(0) NULL,
  `location` VARCHAR(45) NULL,
  `description` VARCHAR(256) NULL,
  `category` VARCHAR(256) NULL,
  PRIMARY KEY (`eventID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Teams` ;

CREATE TABLE IF NOT EXISTS `Teams` (
  `teamID` INT NOT NULL,
  `team_name` VARCHAR(45) NULL,
  PRIMARY KEY (`teamID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Users_has_Teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Users_has_Teams` ;

CREATE TABLE IF NOT EXISTS `Users_has_Teams` (
  `Users_userID` INT NOT NULL,
  `Teams_teamID` INT NOT NULL,
  `isUserAdmin` TINYINT NULL,
  PRIMARY KEY (`Users_userID`, `Teams_teamID`),
  INDEX `fk_Users_has_Teams_Teams1_idx` (`Teams_teamID` ASC),
  INDEX `fk_Users_has_Teams_Users_idx` (`Users_userID` ASC),
  CONSTRAINT `fk_Users_has_Teams_Users`
    FOREIGN KEY (`Users_userID`)
    REFERENCES `Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Teams_Teams1`
    FOREIGN KEY (`Teams_teamID`)
    REFERENCES `Teams` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Users_has_Events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Users_has_Events` ;

CREATE TABLE IF NOT EXISTS `Users_has_Events` (
  `Users_userID` INT NOT NULL,
  `Events_eventID` INT NOT NULL,
  PRIMARY KEY (`Users_userID`, `Events_eventID`),
  INDEX `fk_Users_has_Events_Events1_idx` (`Events_eventID` ASC),
  INDEX `fk_Users_has_Events_Users1_idx` (`Users_userID` ASC),
  CONSTRAINT `fk_Users_has_Events_Users1`
    FOREIGN KEY (`Users_userID`)
    REFERENCES `Users` (`userID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Events_Events1`
    FOREIGN KEY (`Events_eventID`)
    REFERENCES `Events` (`eventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Events_has_Teams`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Events_has_Teams` ;

CREATE TABLE IF NOT EXISTS `Events_has_Teams` (
  `eventID` INT NOT NULL,
  `teamID` INT NOT NULL,
  PRIMARY KEY (`eventID`, `teamID`),
  INDEX `fk_Events_has_Teams_Teams1_idx` (`teamID` ASC),
  INDEX `fk_Events_has_Teams_Events1_idx` (`eventID` ASC),
  CONSTRAINT `fk_Events_has_Teams_Events1`
    FOREIGN KEY (`eventID`)
    REFERENCES `Events` (`eventID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Events_has_Teams_Teams1`
    FOREIGN KEY (`teamID`)
    REFERENCES `Teams` (`teamID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
